<?php

namespace AppBundle\Repository;

/**
 * DetailCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
