<?php

namespace AppBundle\Repository;

/**
 * Membreproduit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Membreproduit extends \Doctrine\ORM\EntityRepository
{
}
